name: Docker Image CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v3
    
    - name: Clone code from other repository
      run: git clone --depth 1 --branch main https://github.com/kastoras/dolibar-dockerfiles.git

    - name: Move Docker Files in root folder
      run: mv dolibar-dockerfiles/* .
      
    - name: Remove Docker Files folder
      run: rm -rf dolibar-dockerfiles

    - name: Checkout original repo to get latest tag
      uses: actions/checkout@v3
      with:
        repository: Dolibarr/dolibarr
        ref: "17.0"

    - name: Checkl current folder
      run: |
        ls -al .
        ls -al ../
        pwd

    - name: Get last tag
      id: get_last_tag
      run: |
        cd dolibarr
        LAST_TAG=$(git describe --abbrev=0 --tags)
        echo "::set-output name=last_tag::$LAST_TAG"        

    - name: Build the Dolibarr Nginx Image Using last tag
      run: |
        LAST_TAG="${{ steps.get_last_tag.outputs.last_tag }}"
        docker build . --file ./dockerfiles/nginx.dockerfile --tag kastoras/dolibarr-nginx:$LAST_TAG
        
    #- name: Build the Dolibarr Nginx Image
    #  run: docker build . --file ./dockerfiles/nginx.dockerfile --tag kastoras/dolibarr-nginx:latest
 
    - name: Log to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push image to docker hub
      run: |
        LAST_TAG="${{ steps.get_last_tag.outputs.last_tag }}"
        docker image push kastoras/dolibarr-nginx:$LAST_TAG
