name: Docker Image CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set the value
      id: step_one
      run: |
          echo "FOO=$(git for-each-ref --sort=-creatordate --format '%(refname:short)' refs/tags --merged v17 | head -n 1)" >> $GITHUB_ENV
    - name: Use the value
      id: step_two
      run: |
          echo "${{ env.FOO }}"
