name: Docker Image CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set the value
      id: step_one
      run: |
          status=$(git status)
          cleaned_status=$(echo "$status" | sed "s/'//g")
          echo "FOO=$cleaned_status" >> $GITHUB_ENV
    - name: Use the value
      id: step_two
      run: |
          echo "${{ env.FOO }}"
