name: Docker Image CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: v17

    - name: Set the value
      id: step_one
      run: |
          echo "FOO=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV
    - name: Use the value
      id: step_two
      run: |
          echo "${{ env.FOO }}"
