name: Docker Image CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v3
    
    - name: Clone code from other repository
      run: git clone --depth 1 --branch main https://github.com/kastoras/dolibar-dockerfiles.git

    - name: Move Docker Files in root folder
      run: mv dolibar-dockerfiles/* .
        
    - name: Check current directory
      run: pwd
    
    - name: List current directory
      run: ls -al . 
      
    - name: Build the Dolibarr Nginx Image
      run: docker build . --file ./dockerfiles/nginx.dockerfile --tag kastoras/dolibarr-nginx:$(date +%s)
 
    - name: Log to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push image to docker hub
      run: docker image push kastoras/dolibarr-nginx:$(date +%s)
