name: Create Dolibarr Docker Image CI Version 19

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
    - name: Checkout Version 19 Branch
      uses: actions/checkout@v3
      with:
          path: v19
    
    - name: Clone code from other repository
      run: git clone --depth 1 --branch main https://github.com/kastoras/dolibar-dockerfiles.git

    - name: Move Docker Files in root folder
      run: mv dolibar-dockerfiles/* .

    - name: Move Dolibarr source code to root
      run: mv v19/htdocs .      

    - name: Create multisite tag version
      run: echo "IMAGE_MULTISITE_TAG=v19-multisite" >> $GITHUB_ENV

    - name: Create simplesite tag version
      run: echo "IMAGE_TAG=v19" >> $GITHUB_ENV      
      
    - name: Build the Dolibarr Singlesite Nginx Image
      run: docker build . --file ./dockerfiles/nginx.dockerfile --tag kastoras/dolibarr-nginx:${{ env.IMAGE_TAG }}

    - name: Build the Dolibarr Singlesite PHP Image
      run: docker build . --file ./dockerfiles/php8.2.withenv.dockerfile --tag kastoras/dolibarr-php:${{ env.IMAGE_TAG }}

    - name: Checkout develop branch for conf.php.serverparams
      run: |
        cd v19
        git fetch origin develop
        git checkout origin/develop -- htdocs/conf/conf.php.serverparams
        mv htdocs/conf/conf.php.serverparams ../htdocs/conf/conf.php
    
    - name: Build the Dolibarr multisite Nginx Image
      run: docker build . --file ./dockerfiles/nginx.dockerfile --tag kastoras/dolibarr-nginx:${{ env.IMAGE_MULTISITE_TAG }}

    - name: Build the Dolibarr multisite PHP Image
      run: docker build . --file ./dockerfiles/php8.2.withenv.dockerfile --tag kastoras/dolibarr-php:${{ env.IMAGE_MULTISITE_TAG }}      
 
    - name: Log to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push images to docker hub
      run: |
        docker image push kastoras/dolibarr-nginx:${{ env.IMAGE_TAG }}
        docker image push kastoras/dolibarr-php:${{ env.IMAGE_TAG }}
        docker image push kastoras/dolibarr-nginx:${{ env.IMAGE_MULTISITE_TAG }}
        docker image push kastoras/dolibarr-php:${{ env.IMAGE_MULTISITE_TAG }}        
